version: "3.7"

services:
  gowebapp:
    build: .
    container_name: gowebappcont
    entrypoint: CompileDaemon --build="go build -o goWebAppLin" --command=./goWebAppLin
    volumes:
      - .:/go/src/goWebApp
    ports:
      - "8080:8080"
    env_file:
      - ".env"
    healthcheck:
      test: "${DOCKER_HEALTHCHECK_TEST:-curl localhost:8080/healthCheck}"
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s