apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file ../docker-compose-tmp.yml convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: gowebapp
  name: gowebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gowebapp
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file ../docker-compose-tmp.yml convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: gowebapp
    spec:
      containers:
      - image: bolbeck/gowebapp
        livenessProbe:
          exec:
            command:
            - curl
            - -f
            - localhost:8080/healthCheck
          failureThreshold: 3
          initialDelaySeconds: 40
          periodSeconds: 90
          timeoutSeconds: 10
        name: gowebappcont
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
